- name: Setup Flask Application
  hosts: ec2
  become: yes
  vars:
    git_username: "flomihciu"
    repo_url: "git@github.com:codeplatoon-devops/user-db-flask.git"  # SSH URL
    ssh_key_path: "/home/ubuntu/.ssh/id_rsa"

  tasks:
    - name: Clone Git repository
      git:
        repo: "{{ repo_url }}"
        dest: /home/ubuntu/user-db-flask
        version: main
        key_file: "{{ ssh_key_path }}"
        accept_hostkey: yes
        update: yes

    - name: Install system dependencies for PostgreSQL
      apt:
        name: libpq-dev
        state: present
        update_cache: yes

    - name: Ensure requirements.txt exists on remote
      stat:
        path: /home/ubuntu/user-db-flask/requirements.txt
      register: requirements_file

    - name: Install Python dependencies
      pip:
        requirements: /home/ubuntu/user-db-flask/requirements.txt
        virtualenv: /opt/todo-app/venv
        virtualenv_command: python3 -m venv
      when: requirements_file.stat.exists

    - name: Configure .env file
      copy:
        dest: /home/ubuntu/user-db-flask/.env
        content: |
          DATABASE_URI=postgresql+psycopg2://flo:password123@{{ groups['rds'][0] }}/mydatabase
          SECRET_KEY=supersecretkey
